### ISSUE TITLE
Select Graphical Front-End Framework

### ISSUE THREAD

**Issue by circuitswitch** [circuitswitch/PivTools#7]
~~Add a graphical front end for functionality~~
Select framework for front-end

Potential Frameworks to Test
- [x] Yad
- [x] [ElectronJS](https://www.electronjs.org/)
   - [x] Encrypt
   - [x] Decrypt
   - [x] Generate .pem from PIV

Findings
- Yad was not found to be natively installed on the MacBook. It can be via HomeBrew; however, we decided to pass on testing this framework in lieu of ElectronJS since installations seem to be unavoidable.

**Comment by mzack5020** [comment]
Potential Frameworks to Test
- [ ] Yad
- [ ] [ElectronJS](https://www.electronjs.org/)

**Comment by mzack5020** [comment]
Testing Electron framework

**Comment by mzack5020** [comment]
> Testing Electron framework

Repo using to start prototype project
https://github.com/maximegris/angular-electron
