### ISSUE TITLE
Encrypt-Decrypt Non-Text Files

### ISSUE THREAD

**Issue by circuitswitch** [circuitswitch/PivTools#8]
Add enhancement to apply PIV based encryption and decryption to non-text files.

**Comment by mzack5020** [comment]
Everything I'm reading is stating we need to gen another key and then encrypt that key using the public cert (RSA) and then encrypt the file with a symmetric encryption (i.e. AES-256)

https://www.czeskis.com/random/openssl-encrypt-file.html
https://raymii.org/s/tutorials/Encrypt_and_decrypt_files_to_public_keys_via_the_OpenSSL_Command_Line.html

**Comment by mzack5020** [comment]
Federal Documentation on PIV Cards
https://piv.idmanagement.gov/details/

**Comment by mzack5020** [comment]
OpenSC Issue describing how to encrypt files of a variety of types. The important piece of information is that the RSA key used for decryption can only be used to decrypt files of k-11 length where k is the length of the key in bytes.
https://github.com/OpenSC/OpenSC/issues/765
